Pin MarkupSafe
MarkupSafe version `3.0.0` introduces an error during rednering of
loadbalancer service templates (e.g. [1])
Temporarily fixed by pining 'MarkupSafe<3.0.0'.

Part of https://github.com/osism/issues/issues/1161

[1]
```
TASK [haproxy-config : Copying over barbican haproxy config] *****************************************************************
task path: /ansible/roles/haproxy-config/tasks/main.yml:2
[...]
SystemError: <built-in function _escape_inner> returned NULL without setting an exception
```

Signed-off-by: Jan Horstmann <horstmann@osism.tech>